import { Types } from "mongoose";
import {
    addEthiopianMonths,
    ethiopianToGregorian,
    formatEthiopianDate,
    getCurrentEthiopianDate,
    gregorianToEthiopian,
    parseEthiopianDate,
    type EthiopianDate
} from "../../common/utils/ethiopianCalendar";
import { User } from "../auth/user.model";
import { Payment, PaymentDoc } from "./payment.model";
import { Salary, SalaryDoc } from "./salary.model";
import { Withdrawal, WithdrawalDoc } from "./withdrawal.model";

export interface CreateSalaryInput {
  staffId: string;
  amount: number;
  month?: string; // YYYY-MM (Gregorian) - auto-calculated
  year?: number; // Gregorian year - auto-calculated
  paymentDate?: string | Date; // Gregorian payment date
  status?: "pending" | "paid";
  remarks?: string;
  clientId?: string; // For offline sync idempotency

  // Ethiopian calendar fields (optional)
  registeredDate?: string; // YYYY-MM-DD (Ethiopian)
  ethiopianPaymentDate?: string; // YYYY-MM-DD (Ethiopian)
  salaryPeriod?: "monthly" | "per_month";
}

export interface UpdateSalaryInput {
  amount?: number;
  status?: "pending" | "paid";
  paymentDate?: Date;
  remarks?: string;
  ethiopianPaymentDate?: string;
  registeredDate?: string; // YYYY-MM-DD (Ethiopian)
  salaryPeriod?: "monthly" | "per_month";
}

export interface CreateWithdrawalInput {
  amount: number;
  reason:
    | "cash"
    | "broke_products"
    | "advance"
    | "deduction"
    | "loan"
    | "other";
  description?: string;
}

export interface CreatePaymentInput {
  amount: number;
  paymentDate?: Date;
  paymentMethod?: "cash" | "bank_transfer" | "check" | "mobile_money" | "other";
  remarks?: string;
  isAutoGenerated?: boolean; // Flag to prevent status change for auto-payments
}

export interface ListSalaryFilters {
  staffId?: string;
  month?: string;
  year?: number;
  status?: "pending" | "paid";
  page?: number;
  limit?: number;
}

export const listSalaries = async (filters: ListSalaryFilters = {}) => {
  const { staffId, month, year, status, page = 1, limit = 50 } = filters;
  const query: any = {};

  if (staffId) {
    query.staffId = new Types.ObjectId(staffId);
  }

  if (month) {
    query.month = month;
  }

  if (year) {
    query.year = year;
  }

  if (status) {
    query.status = status;
  }

  const skip = (page - 1) * limit;

  const [salaries, total] = await Promise.all([
    Salary.find(query)
      .populate("staffId", "name email phone role")
      .populate("createdBy", "name email")
      .sort({ year: -1, month: -1, createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean(),
    Salary.countDocuments(query),
  ]);

  return {
    salaries,
    pagination: {
      page,
      limit,
      total,
      pages: Math.ceil(total / limit),
    },
  };
};

export const getSalaryById = async (id: string): Promise<SalaryDoc | null> => {
  const salary = await Salary.findById(id)
    .populate("staffId", "name email phone role")
    .populate("createdBy", "name email")
    .lean();

  return salary as any;
};

export const createSalary = async (
  data: CreateSalaryInput,
  createdBy: string
): Promise<SalaryDoc> => {
  // Check for idempotency if clientId provided
  if (data.clientId) {
    const existing = await Salary.findOne({ clientId: data.clientId });
    if (existing) {
      await existing.populate("staffId", "name email phone role");
      await existing.populate("createdBy", "name email");
      return existing;
    }
  }

  // Validate amount
  if (data.amount <= 0) {
    throw { status: 400, message: "Amount must be greater than 0" };
  }

  // Validate staff exists and is not deleted
  const staff = await User.findOne({
    _id: data.staffId,
    isDeleted: { $ne: true },
  });
  if (!staff) {
    throw { status: 404, message: "Staff member not found" };
  }

  // Handle dates: prioritize Gregorian if provided, otherwise parse Ethiopian
  let registeredEthDate: EthiopianDate;
  let paymentEthDate: EthiopianDate;
  let gregorianPaymentDate: Date;

  if (data.paymentDate && (typeof data.paymentDate === "object" || !/^\d{4}-\d{2}-\d{2}$/.test(data.paymentDate as string))) {
    // Standard JS Date or ISO string
    gregorianPaymentDate = new Date(data.paymentDate);
    paymentEthDate = gregorianToEthiopian(gregorianPaymentDate);
  } else if (typeof data.paymentDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(data.paymentDate)) {
    // Check if it's actually an Ethiopian format YYYY-MM-DD being passed in paymentDate
    // This is for backward compatibility or if the field is misused
    try {
      paymentEthDate = parseEthiopianDate(data.paymentDate);
      gregorianPaymentDate = ethiopianToGregorian(paymentEthDate);
    } catch {
      // Fallback to Gregorian
      gregorianPaymentDate = new Date(data.paymentDate);
      paymentEthDate = gregorianToEthiopian(gregorianPaymentDate);
    }
  } else if ((data as any).ethiopianPaymentDate) {
    paymentEthDate = parseEthiopianDate((data as any).ethiopianPaymentDate);
    gregorianPaymentDate = ethiopianToGregorian(paymentEthDate);
  } else {
    // Default to 1 month from now
    const now = new Date();
    const future = new Date();
    future.setMonth(now.getMonth() + 1);
    gregorianPaymentDate = future;
    paymentEthDate = gregorianToEthiopian(gregorianPaymentDate);
  }

  if (data.registeredDate) {
    registeredEthDate = parseEthiopianDate(data.registeredDate);
  } else {
    // Default to now
    registeredEthDate = getCurrentEthiopianDate();
  }

  const gregorianMonth = `${gregorianPaymentDate.getFullYear()}-${String(
    gregorianPaymentDate.getMonth() + 1
  ).padStart(2, "0")}`;
  const gregorianYear = gregorianPaymentDate.getFullYear();

  // Check for duplicate - simple check by staffId only (allow multiple records)
  // Or check if there's an active salary for this staff
  const existing = await Salary.findOne({
    staffId: data.staffId,
    status: "pending",
  });

  if (existing) {
    throw {
      status: 409,
      message: "There is already a pending salary record for this staff member",
    };
  }

  const salary = await Salary.create({
    staffId: new Types.ObjectId(data.staffId),
    amount: data.amount,
    month: gregorianMonth,
    year: gregorianYear,
    paymentDate: gregorianPaymentDate,
    status: data.status || "pending",
    remarks: data.remarks || "",
    createdBy: new Types.ObjectId(createdBy),
    clientId: data.clientId,

    // Ethiopian calendar fields
    ethiopianMonth: paymentEthDate.month,
    ethiopianYear: paymentEthDate.year,
    ethiopianPaymentDate: formatEthiopianDate(paymentEthDate),
    registeredDate: formatEthiopianDate(registeredEthDate),
    salaryPeriod: data.salaryPeriod || "monthly",

    // Initialize tracking fields
    netAmount: data.amount,
    totalWithdrawals: 0,
    totalPayments: 0,
  });

  await salary.populate("staffId", "name email phone role");
  await salary.populate("createdBy", "name email");

  return salary;
};

export const updateSalary = async (
  id: string,
  data: UpdateSalaryInput
): Promise<SalaryDoc | null> => {
  const salary = await Salary.findById(id);

  if (!salary) {
    throw { status: 404, message: "Salary record not found" };
  }

  if (data.amount !== undefined) {
    if (data.amount <= 0) {
      throw { status: 400, message: "Amount must be greater than 0" };
    }
    salary.amount = data.amount;
  }

  if (data.status) {
    salary.status = data.status;
  }

  if (data.paymentDate) {
    salary.paymentDate = data.paymentDate;
  }

  if (data.remarks !== undefined) {
    salary.remarks = data.remarks;
  }

  if (data.ethiopianPaymentDate) {
    const ethDate = parseEthiopianDate(data.ethiopianPaymentDate);
    salary.ethiopianPaymentDate = data.ethiopianPaymentDate;
    salary.ethiopianMonth = ethDate.month;
    salary.ethiopianYear = ethDate.year;

    // Update Gregorian payment date from Ethiopian date
    const gregorianDate = ethiopianToGregorian(ethDate);
    salary.paymentDate = gregorianDate;
    salary.month = `${gregorianDate.getFullYear()}-${String(
      gregorianDate.getMonth() + 1
    ).padStart(2, "0")}`;
    salary.year = gregorianDate.getFullYear();
  }

  if (data.salaryPeriod) {
    salary.salaryPeriod = data.salaryPeriod;
  }

  // Handle registeredDate update
  if (data.registeredDate) {
    const registeredEthDate = parseEthiopianDate(data.registeredDate);
    salary.registeredDate = data.registeredDate;
  }

  // Handle paymentDate update (Ethiopian)
  if (data.ethiopianPaymentDate) {
    const paymentEthDate = parseEthiopianDate(data.ethiopianPaymentDate);
    salary.ethiopianPaymentDate = data.ethiopianPaymentDate;
    salary.ethiopianMonth = paymentEthDate.month;
    salary.ethiopianYear = paymentEthDate.year;

    // Update Gregorian payment date from Ethiopian date
    const gregorianPaymentDate = ethiopianToGregorian(paymentEthDate);
    salary.paymentDate = gregorianPaymentDate;
    salary.month = `${gregorianPaymentDate.getFullYear()}-${String(
      gregorianPaymentDate.getMonth() + 1
    ).padStart(2, "0")}`;
    salary.year = gregorianPaymentDate.getFullYear();
  }

  // Recalculate net amount
  salary.netAmount = salary.amount - (salary.totalWithdrawals || 0);

  await salary.save();

  await salary.populate("staffId", "name email phone role");
  await salary.populate("createdBy", "name email");

  return salary;
};

export const deleteSalary = async (id: string): Promise<void> => {
  const salary = await Salary.findById(id);

  if (!salary) {
    throw { status: 404, message: "Salary record not found" };
  }

  // Delete associated withdrawals
  await Withdrawal.deleteMany({ salaryId: id });

  // Delete associated payments
  await Payment.deleteMany({ salaryId: id });

  // Delete the salary record
  await Salary.findByIdAndDelete(id);
};

export const getSalarySummary = async (filters: {
  month?: string;
  year?: number;
}) => {
  const { month, year } = filters;
  const matchQuery: any = {};

  if (month) {
    matchQuery.month = month;
  }

  if (year) {
    matchQuery.year = year;
  }

  const summary = await Salary.aggregate([
    { $match: matchQuery },
    {
      $group: {
        _id: "$staffId",
        totalAmount: { $sum: "$amount" },
        count: { $sum: 1 },
        paidCount: {
          $sum: { $cond: [{ $eq: ["$status", "paid"] }, 1, 0] },
        },
        pendingCount: {
          $sum: { $cond: [{ $eq: ["$status", "pending"] }, 1, 0] },
        },
      },
    },
    {
      $lookup: {
        from: "users",
        localField: "_id",
        foreignField: "_id",
        as: "staff",
      },
    },
    { $unwind: "$staff" },
    {
      $project: {
        staffId: "$_id",
        staffName: "$staff.name",
        staffEmail: "$staff.email",
        staffPhone: "$staff.phone",
        totalAmount: 1,
        count: 1,
        paidCount: 1,
        pendingCount: 1,
      },
    },
    { $sort: { totalAmount: -1 } },
  ]);

  const totals = await Salary.aggregate([
    { $match: matchQuery },
    {
      $group: {
        _id: null,
        totalAmount: { $sum: "$amount" },
        totalCount: { $sum: 1 },
        totalPaid: {
          $sum: { $cond: [{ $eq: ["$status", "paid"] }, "$amount", 0] },
        },
        totalPending: {
          $sum: { $cond: [{ $eq: ["$status", "pending"] }, "$amount", 0] },
        },
      },
    },
  ]);

  return {
    summary,
    totals: totals[0] || {
      totalAmount: 0,
      totalCount: 0,
      totalPaid: 0,
      totalPending: 0,
    },
  };
};

export const getStaffSalaryHistory = async (staffId: string) => {
  const salaries = await Salary.find({ staffId: new Types.ObjectId(staffId) })
    .populate("createdBy", "name email")
    .sort({ year: -1, month: -1 })
    .lean();

  return salaries;
};

/* ---------------------- WITHDRAWAL MANAGEMENT ---------------------- */

export const createWithdrawal = async (
  salaryId: string,
  data: CreateWithdrawalInput,
  createdBy: string
): Promise<WithdrawalDoc> => {
  const salary = await Salary.findById(salaryId);
  if (!salary) {
    throw { status: 404, message: "Salary record not found" };
  }

  if (data.amount <= 0) {
    throw { status: 400, message: "Withdrawal amount must be greater than 0" };
  }

  // Calculate current net amount
  const currentNetAmount = salary.amount - (salary.totalWithdrawals || 0);

  if (data.amount > currentNetAmount) {
    throw {
      status: 400,
      message: `Withdrawal amount (${data.amount}) cannot exceed available amount (${currentNetAmount})`,
    };
  }

  const withdrawal = await Withdrawal.create({
    salaryId: new Types.ObjectId(salaryId),
    amount: data.amount,
    reason: data.reason,
    description: data.description,
    createdBy: new Types.ObjectId(createdBy),
  });

  // Update salary totals
  salary.totalWithdrawals = (salary.totalWithdrawals || 0) + data.amount;
  salary.netAmount = salary.amount - salary.totalWithdrawals;
  await salary.save();

  await withdrawal.populate("createdBy", "name email");
  return withdrawal;
};

export const listWithdrawals = async (salaryId: string) => {
  const withdrawals = await Withdrawal.find({
    salaryId: new Types.ObjectId(salaryId),
  })
    .populate("createdBy", "name email")
    .sort({ createdAt: -1 })
    .lean();

  return withdrawals;
};

export const deleteWithdrawal = async (withdrawalId: string): Promise<void> => {
  const withdrawal = await Withdrawal.findById(withdrawalId);
  if (!withdrawal) {
    throw { status: 404, message: "Withdrawal not found" };
  }

  const salary = await Salary.findById(withdrawal.salaryId);
  if (salary) {
    // Revert withdrawal amount
    salary.totalWithdrawals = Math.max(
      0,
      (salary.totalWithdrawals || 0) - withdrawal.amount
    );
    salary.netAmount = salary.amount - salary.totalWithdrawals;
    await salary.save();
  }

  await Withdrawal.findByIdAndDelete(withdrawalId);
};

/* ---------------------- PAYMENT MANAGEMENT ---------------------- */

export const createPayment = async (
  salaryId: string,
  data: CreatePaymentInput,
  createdBy: string
): Promise<PaymentDoc> => {
  const salary = await Salary.findById(salaryId);
  if (!salary) {
    throw { status: 404, message: "Salary record not found" };
  }

  if (data.amount <= 0) {
    throw { status: 400, message: "Payment amount must be greater than 0" };
  }

  // Calculate remaining balance
  const remainingBalance =
    (salary.netAmount || salary.amount) - (salary.totalPayments || 0);

  if (data.amount > remainingBalance) {
    throw {
      status: 400,
      message: `Payment amount (${data.amount}) cannot exceed remaining balance (${remainingBalance})`,
    };
  }

  const payment = await Payment.create({
    salaryId: new Types.ObjectId(salaryId),
    amount: data.amount,
    paymentDate: data.paymentDate || new Date(),
    paymentMethod: data.paymentMethod,
    remarks: data.remarks,
    isAutoGenerated: data.isAutoGenerated || false,
    createdBy: new Types.ObjectId(createdBy),
  });

  // Update salary totals
  salary.totalPayments = (salary.totalPayments || 0) + data.amount;

  // Update status if fully paid - but only for manual payments (not auto-generated)
  // Auto-generated payments should keep status as "pending" until user manually records payment
  if (!data.isAutoGenerated) {
    const newRemainingBalance =
      (salary.netAmount || salary.amount) - salary.totalPayments;
    if (newRemainingBalance <= 0) {
      salary.status = "paid";
    }
  }

  await salary.save();

  await payment.populate("createdBy", "name email");
  return payment;
};

export const listPayments = async (salaryId: string) => {
  const payments = await Payment.find({
    salaryId: new Types.ObjectId(salaryId),
  })
    .populate("createdBy", "name email")
    .sort({ paymentDate: -1 })
    .lean();

  return payments;
};

export const deletePayment = async (paymentId: string): Promise<void> => {
  const payment = await Payment.findById(paymentId);
  if (!payment) {
    throw { status: 404, message: "Payment not found" };
  }

  const salary = await Salary.findById(payment.salaryId);
  if (salary) {
    // Revert payment amount
    salary.totalPayments = Math.max(
      0,
      (salary.totalPayments || 0) - payment.amount
    );

    // Recalculate status
    const remainingBalance =
      (salary.netAmount || salary.amount) - salary.totalPayments;
    if (remainingBalance > 0) {
      salary.status = "pending";
    }

    await salary.save();
  }

  await Payment.findByIdAndDelete(paymentId);
};

/* ---------------------- AUTO-PAYMENT AND ROLLOVER ---------------------- */

/**
 * Auto-create payment when countdown reaches 0
 * This payment is created automatically but status remains "pending" until user manually records payment
 */
export const autoCreatePaymentOnDueDate = async (
  salaryId: string
): Promise<PaymentDoc | null> => {
  const salary = await Salary.findById(salaryId);
  if (!salary) {
    return null;
  }

  // Only create auto-payment if status is still pending
  if (salary.status !== "pending") {
    return null;
  }

  // Check if auto-payment already exists (prevent duplicates)
  const existingAutoPayment = await Payment.findOne({
    salaryId: new Types.ObjectId(salaryId),
    isAutoGenerated: true,
  });

  if (existingAutoPayment) {
    return existingAutoPayment;
  }

  // Calculate remaining balance
  const remainingBalance =
    (salary.netAmount || salary.amount) - (salary.totalPayments || 0);

  // Only create if there's a remaining balance
  if (remainingBalance <= 0) {
    return null;
  }

  // Create auto-payment for the full remaining balance
  const payment = await Payment.create({
    salaryId: new Types.ObjectId(salaryId),
    amount: remainingBalance,
    paymentDate: new Date(),
    paymentMethod: "other",
    remarks: "Auto-generated on due date",
    isAutoGenerated: true,
    // Use system user or the original creator as createdBy
    createdBy: salary.createdBy,
  });

  // Update salary totals but keep status as "pending"
  salary.totalPayments = (salary.totalPayments || 0) + remainingBalance;
  await salary.save();

  await payment.populate("createdBy", "name email");
  return payment;
};

/**
 * Auto-rollover dates to next month when payment date passes
 * Only updates dates, does not change status or create new salary record
 */
export const autoRolloverToNextMonth = async (
  salaryId: string
): Promise<boolean> => {
  const salary = await Salary.findById(salaryId);
  if (!salary) {
    return false;
  }

  // Only rollover if status is still pending
  if (salary.status !== "pending") {
    return false;
  }

  if (!salary.ethiopianPaymentDate) {
    return false;
  }

  // Get current Ethiopian date
  const currentEthDate = getCurrentEthiopianDate();
  const paymentDate = parseEthiopianDate(salary.ethiopianPaymentDate);

  // Check if payment date has passed (current date > payment date)
  const currentGreg = ethiopianToGregorian(currentEthDate);
  const paymentGreg = ethiopianToGregorian({
    year: currentEthDate.year,
    month: paymentDate.month,
    day: paymentDate.day,
  });

  // If payment date hasn't passed yet, don't rollover
  if (currentGreg <= paymentGreg) {
    return false;
  }

  // Update registered date to current date
  const newRegisteredDate = formatEthiopianDate(currentEthDate);
  salary.registeredDate = newRegisteredDate;

  // Update payment date to 1 month from current registered date
  const newPaymentEthDate = addEthiopianMonths(currentEthDate, 1);
  const newPaymentDateStr = formatEthiopianDate(newPaymentEthDate);
  salary.ethiopianPaymentDate = newPaymentDateStr;

  // Update Ethiopian month and year
  salary.ethiopianMonth = newPaymentEthDate.month;
  salary.ethiopianYear = newPaymentEthDate.year;

  // Convert new payment date to Gregorian and update related fields
  const newPaymentGreg = ethiopianToGregorian(newPaymentEthDate);
  salary.paymentDate = newPaymentGreg;
  salary.month = `${newPaymentGreg.getFullYear()}-${String(
    newPaymentGreg.getMonth() + 1
  ).padStart(2, "0")}`;
  salary.year = newPaymentGreg.getFullYear();

  await salary.save();
  return true;
};

/* ---------------------- COUNTDOWN CALCULATION ---------------------- */

export const calculateCountdown = async (salaryId: string) => {
  const salary = await Salary.findById(salaryId);
  if (!salary) {
    throw { status: 404, message: "Salary record not found" };
  }

  // Get current Gregorian date
  const now = new Date();
  
  // Use Gregorian payment date as primary if possible
  const paymentDateGreg = salary.paymentDate;
  
  // Calculate daysUntil using Gregorian dates
  const diffMs = paymentDateGreg.getTime() - now.getTime();
  const daysUntil = Math.max(0, Math.ceil(diffMs / (1000 * 60 * 60 * 24)));

  // Use Gregorian for primary countdown
  const nextPaymentGregorian = new Date(salary.paymentDate);
  if (now > nextPaymentGregorian && salary.status === "pending") {
    // If due date passed, rollover or show 0
    // Actually, autoRollover is called below
  }

  // Fallback to Ethiopian for backward compatibility if needed, 
  // but prioritize Gregorian for logic.
  const registeredDateEth = salary.registeredDate ? parseEthiopianDate(salary.registeredDate) : gregorianToEthiopian(salary.createdAt || new Date());
  const paymentDateEth = salary.ethiopianPaymentDate ? parseEthiopianDate(salary.ethiopianPaymentDate) : gregorianToEthiopian(salary.paymentDate);
  const currentEthDate = getCurrentEthiopianDate();

  // Calculate totalDays between registered and payment (Gregorian based)
  const registeredGregorian = salary.createdAt || new Date();
  const totalDaysDiffMs = nextPaymentGregorian.getTime() - registeredGregorian.getTime();
  const totalDays = Math.max(1, Math.ceil(totalDaysDiffMs / (1000 * 60 * 60 * 24)));

  // Auto-create payment if countdown reached 0 and status is pending
  if (daysUntil === 0 && salary.status === "pending") {
    await autoCreatePaymentOnDueDate(salaryId);
  }

  // Auto-rollover dates if payment date has passed and status is pending
  if (salary.status === "pending" && now > nextPaymentGregorian) {
    await autoRolloverToNextMonth(salaryId);

    // Reload salary to get updated dates if rollover occurred
    const updatedSalary = await Salary.findById(salaryId);
    if (updatedSalary && updatedSalary.paymentDate.getTime() !== salary.paymentDate.getTime()) {
      const updatedDiffMs = updatedSalary.paymentDate.getTime() - now.getTime();
      const updatedDaysUntil = Math.max(0, Math.ceil(updatedDiffMs / (1000 * 60 * 60 * 24)));
      
      const updatedTotalDaysDiffMs = updatedSalary.paymentDate.getTime() - (updatedSalary.createdAt || new Date()).getTime();
      const updatedTotalDays = Math.max(1, Math.ceil(updatedTotalDaysDiffMs / (1000 * 60 * 60 * 24)));

      return {
        daysUntil: updatedDaysUntil,
        totalDays: updatedTotalDays,
        nextPaymentDate: {
          ethiopian: updatedSalary.ethiopianPaymentDate || "",
          gregorian: updatedSalary.paymentDate.toISOString(),
        },
        registeredDate: updatedSalary.registeredDate || "",
        registeredDateGregorian: (updatedSalary.createdAt || new Date()).toISOString(),
      };
    }
  }

  return {
    daysUntil,
    totalDays, 
    nextPaymentDate: {
      ethiopian: salary.ethiopianPaymentDate || "",
      gregorian: nextPaymentGregorian.toISOString(),
    },
    registeredDate: salary.registeredDate || "",
    registeredDateGregorian: (salary.createdAt || new Date()).toISOString(),
  };
};

/* ---------------------- NET AMOUNT CALCULATION ---------------------- */

export const getNetAmount = async (salaryId: string): Promise<number> => {
  const salary = await Salary.findById(salaryId);
  if (!salary) {
    throw { status: 404, message: "Salary record not found" };
  }

  // Recalculate from withdrawals
  const withdrawals = await Withdrawal.find({
    salaryId: new Types.ObjectId(salaryId),
  }).lean();

  const totalWithdrawals = withdrawals.reduce((sum, w) => sum + w.amount, 0);

  const netAmount = salary.amount - totalWithdrawals;

  // Update salary record
  salary.totalWithdrawals = totalWithdrawals;
  salary.netAmount = netAmount;
  await salary.save();

  return netAmount;
};
